### ISSUE TITLE
Meson 0.57を使ったとき test サブコマンドが失敗する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#613]
**バグの説明**

Meson 0.57の **test** サブコマンドでテストプログラムをビルドするとエラーメッセージが出て失敗します。
0.56ではエラーが出ずテストを実行できます。

edit: 0.57.1でもエラーが出て失敗しました。

エラーメッセージ
```sh
[222/273] Compiling C++ object test/gtest_jdim.p/.._src_environment.cpp.o
FAILED: test/gtest_jdim.p/.._src_environment.cpp.o
ccache c++ -Itest/gtest_jdim.p -Itest -I../test -Isrc -I../src -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/p11-kit-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++1z -g -DHAVE_CONFIG_H=1 '-DGTK_DOMAIN="gtk30"' -Wno-unused-parameter -pthread -Wl,--start-group -lpthread -Wl,--end-group -DGTEST_HAS_PTHREAD=1 -MD -MQ test/gtest_jdim.p/.._src_environment.cpp.o -MF test/gtest_jdim.p/.._src_environment.cpp.o.d -o test/gtest_jdim.p/.._src_environment.cpp.o -c ../src/environment.cpp
In file included from ../src/environment.cpp:10:
../src/jdversion.h:10:10: fatal error: buildinfo.h: そのようなファイルやディレクトリはありません
   10 | #include "buildinfo.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**再現の方法**

Meson 0.57をインストールして端末から `meson test` を実行します。
```sh
$ meson --version
0.57.0

$ meson t057
(snip)

$ meson test -C t057
(snip)
# 上記のエラーメッセージが出る
```

**やりたかったこと・期待する結果**

testサブコマンドでテストのビルドと実行をする。

**スクリーンショット**

なし

**動作環境**

```
[バージョン] JDim 0.5.0-20210221(git:d9d1ddddf4)
[ディストリ ] Ubuntu 20.10 (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] KDE
[　gtkmm 　] 3.24.2
[　glibmm 　] 2.64.2
[　TLS lib　] GnuTLS 3.6.15
[ そ の 他 ] 
```

**追加の情報**

**compile** サブコマンドでビルドするときはエラーが出ませんでした。
```sh
$ meson --version
0.57.0

$ meson b057
(snip)

$ meson compile -C b057
ninja: Entering directory `b057'
[318/318] Linking target test/gtest_jdim

$ meson test -C b057
[1/3] Generating buildinfo.h with a custom command (wrapped by meson to capture output)
1/1 gtest tests        OK              0.04s
(snip)
```

Meson 0.57の更新で **test** サブコマンドはテストプログラムのみ再ビルドするように変更されたようです。
https://mesonbuild.com/Release-notes-for-0-57-0.html#meson-test-only-rebuilds-test-dependencies
> Until now, meson test rebuilt the whole project independent of the requested tests and their dependencies. With this release, meson test will only rebuild what is needed for the tests or suites that will be run. 
> (snip)
> However, this change could cause failures when upgrading to 0.57, if the dependencies are not specified correctly in meson.build.
